language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: CHsC7TgoTRYrq71Zxr4cVF91oE7dHVmSt4BjMtdvkyE/22NPa4ViuwSXIdbYD4kXuNFmXiRKo7+ZcIy3HfiohSbysplO38nM2gr0DekWuiwm8vshN9dQfpwbkUnxydqJVo+SBg3APGoAi4boSrYa4HGmIXFW7fAi8dDPa8TGdCIYDNLe4bc/0AiQWO3zL/gPbMSR9JZxZZGNaaOTBUSQjQ3StbF68LfwGqf7IuBSPJ4HwqRNCGqiC9RNztAtSE4SH3kjFwfQGHZ45033bQRYmKfWqkBDq2KpVWhLkLvQoO3d+qOmW30fwNlI+ja+pfmbz9k3wpc5chOpr4F5Zym2n69Pj8iPHGntto0qmaRHe66DESbwujCXUjrGwjL3HEGa+hRXVCz2zonrIxixZ3ewusiLDk3kCQspoBxIsfkRquX+1qUItJxyv3NIznJAgA+Ss68vLDadY/39N7MbRfZAGj7FSZlR0CrliMkn4SaelG9b/IBJ51YdHVwQpdegjrXZCOU0A1PDpRve+jlKB3jSboTeVtS9zREiy82fgs+ggAstRRocIyUeAX3MuNx2qhTMCDM4f5OLBzfH3h6V5o2qku6D/wL1pFtRkeL9owMCPtiGMwA/6qwJH7+rQD0fOO474skRcX7zLVSxuihbV8Fv8zmaiCNDesPO/FqvhcwR5Ac=
  app: fast-meadow-25618
  on:
    repo: kdxcii/my-automate-client
